# Generated by Django 6.1.1 on 2026-09-03 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Congregation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nome da congregação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Congregação',
                'verbose_name_plural': 'Congregações',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('congregation', models.ForeignKey(blank=True, help_text='Deixe em branco para acesso geral (todas as congregações).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admins', to='core.congregation', verbose_name='Congregação')),
            ],
            options={
                'verbose_name': 'Perfil de administrador',
                'verbose_name_plural': 'Perfis de administradores',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('event_date', models.DateTimeField(verbose_name='Data e hora')),
                ('location', models.CharField(blank=True, max_length=250, verbose_name='Local')),
                ('image', models.ImageField(blank=True, null=True, upload_to='eventos/%Y/%m/', verbose_name='Imagem do evento')),
                ('published', models.BooleanField(default=True, verbose_name='Publicado no site público')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('congregation', models.ForeignKey(blank=True, help_text='Deixe em branco para um evento geral do Setor 46 (todas as congregações).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.congregation', verbose_name='Congregação')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['-event_date'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Nome completo')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Data de nascimento')),
                ('cargo', models.CharField(choices=[('membro', 'Membro'), ('cooperador', 'Cooperador'), ('diacono', 'Diácono'), ('presbitero', 'Presbítero'), ('evangelista', 'Evangelista'), ('pastor', 'Pastor')], default='membro', max_length=20, verbose_name='Cargo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('congregation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='members', to='core.congregation', verbose_name='Congregação')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Membro',
                'verbose_name_plural': 'Membros',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Minute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('meeting_date', models.DateField(verbose_name='Data da reunião')),
                ('file', models.FileField(blank=True, null=True, upload_to='atas/%Y/%m/', verbose_name='Arquivo (PDF)')),
                ('notes', models.TextField(blank=True, verbose_name='Anotações / resumo')),
                ('published', models.BooleanField(default=True, verbose_name='Publicada no site público')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('congregation', models.ForeignKey(blank=True, help_text='Deixe em branco para uma ata geral do Setor 46 (todas as congregações).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='minutes', to='core.congregation', verbose_name='Congregação')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ata de reunião',
                'verbose_name_plural': 'Atas de reuniões',
                'ordering': ['-meeting_date'],
            },
        ),
    ]
