# Generated by Django 6.1.1 on 2026-09-03 17:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_grupo_admin_congregacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minute',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='atas/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Arquivo (PDF)'),
        ),
    ]
