# Generated by Django 6.1.1 on 2026-09-04 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_restringe_grupo_so_membros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminprofile',
            name='congregation',
            field=models.ForeignKey(blank=True, help_text='Deixe em branco para acesso geral (todas as congregações).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admins', to='core.congregation', verbose_name='Congregação'),
        ),
        migrations.AlterField(
            model_name='event',
            name='congregation',
            field=models.ForeignKey(blank=True, help_text='Deixe em branco para um evento geral do Setor 46 (todas as congregações).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='core.congregation', verbose_name='Congregação'),
        ),
        migrations.AlterField(
            model_name='minute',
            name='congregation',
            field=models.ForeignKey(blank=True, help_text='Deixe em branco para uma ata geral do Setor 46 (todas as congregações).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='minutes', to='core.congregation', verbose_name='Congregação'),
        ),
    ]
