# Generated by Django 6.1.1 on 2026-09-05 17:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_adminprofile_congregation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_referencia', models.DateField(help_text='Escolha qualquer dia do mês a que a mensalidade se refere (ex: 01/09/2026 para setembro/2026).', verbose_name='Mês de referência')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Valor pago')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Data do Pix')),
                ('comprovante', models.FileField(help_text='PDF ou foto (JPG/PNG) do comprovante do Pix.', upload_to='comprovantes/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='Comprovante')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('confirmado', models.BooleanField(default=False, verbose_name='Confirmado pelo administrador geral')),
                ('confirmado_em', models.DateTimeField(blank=True, null=True, verbose_name='Confirmado em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Enviado em')),
                ('confirmado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Confirmado por')),
                ('congregation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mensalidades', to='core.congregation', verbose_name='Congregação')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mensalidade',
                'verbose_name_plural': 'Mensalidades',
                'ordering': ['-mes_referencia', 'congregation__name'],
                'constraints': [models.UniqueConstraint(fields=('congregation', 'mes_referencia'), name='unica_mensalidade_por_congregacao_mes')],
            },
        ),
    ]
