# Generated by Django 6.1.1 on 2026-09-05 18:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_grupo_congregacao_mensalidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensalidade',
            name='comprovante',
            field=models.FileField(blank=True, help_text='PDF ou foto (JPG/PNG) do comprovante do Pix.', upload_to='comprovantes/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='Comprovante'),
        ),
    ]
