# Generated by Django 6.1.1 on 2026-09-05 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_mensalidade_comprovante'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensalidade',
            name='marcado_atrasado',
            field=models.BooleanField(default=False, help_text='Só o administrador geral vê este campo — força este mês a aparecer como atrasado mesmo antes de o mês terminar (ex: a congregação já passou do prazo interno combinado).', verbose_name='Marcar como atrasado'),
        ),
    ]
